### ISSUE TITLE
Ignore certain pages? 

### ISSUE THREAD

**Issue by xdcha** [geeogi/nuxt-responsive-loader#4]
This is a great plugin but it is overriding my own custom Srcsets that I have had to make for my homepage slider using swiper.js. 

```
  /*
   ** Nuxt.js modules
   */
  modules: ["nuxt-responsive-loader"],

  responsiveLoader: {
    name: "img-[hash:14].[width].[ext]",
    min: 340,
    max: 1920,
    steps: 5,
    placeholder: false,
    quality: 75
  },
```

Is there a way I can tell this module to ignore a certain Route? Like the homepage for example? 

My own Srcset on my homepage `pages/index.vue`

```
 <figure class="c-home-project-img u-fit u-relative">
      <img
        class="swiper-lazy c-img-inner"
        :src="imgSources.srcPath"
        :alt="projectImgAlt"
        :srcset="imgSources.srcSetPath1 + ' 320w, ' 
        + imgSources.srcSetPath2 + ' 1020w, ' 
        + imgSources.srcSetPath3 + ' 1920w'"
        sizes="100vw"
      />
    </figure>
```

```
export default {
  computed: {
    imgSources() {
      return {
        srcPath: require(`~/assets/img/home/slider${this.projectPath}/${this.projectImg}.jpg`),
        srcSetPath1: require(`~/assets/img/home/slider${this.projectPath}/${this.projectImg}.jpg`),
        srcSetPath2: require(`~/assets/img/home/slider${this.projectPath}/${this.projectImg}@2.jpg`),
        srcSetPath3: require(`~/assets/img/home/slider${this.projectPath}/${this.projectImg}@3.jpg`)
      };
    }
  }
};
```

Interesting how here I am not using `.srcSet` but it is applying the module to the above?

**Comment by geeogi** [comment]
Hi there, glad you're enjoying the module 👍  

So, this module will process all images located in `assets` folder and will rewire all `require('~assets/...')` references in your Nuxt project. There's no way to opt-out of particular files/routes. 

I have two suggestions: 

1) I'm not familiar with slider.js, but since you're using a srcSet for an `img` element then you should be able to use the usual template structure which is described in the ReadMe for this module e.g. 

```
 <img
        class="swiper-lazy c-img-inner"
        :alt="projectImgAlt"
        :srcset="require('~/assets/img/home/mySliderJsImage.srcSet')"
      />
```

Just make sure there's a single image located in `/assets/img/home/mySliderJsImage.png/jpg`. That way, your slider.js image will be processed by the module in the usual way described in the ReadMe.

2) If you definitely need to configure responsive-loader on a per-file basis then you could write a custom web pack configuration in your project (instead of using this module). You could take a look at the source code for this module and view this Nuxt.js reference for some guidance on going about that: https://nuxtjs.org/faq/extend-webpack/. It's possible to exclude particular files in the web pack rules. 

The first option would be simpler I think (again, I'm not familiar with slider.js so I could be missing something).

**Comment by xdcha** [comment]
Many thanks indeed. It is mainly down to crops. A full-width slider image on mobile is a different proportion to a desktop version. I see you mention another library that crops too but I fear this is a little too intense. I think perhaps your section option seems most ideal. Thanks very much for getting back to me. -David
